build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

filter:
  excluded_paths:
    - "tests/"
    # Everything in a root level "tests" directory will be excluded

checks:
  php: true

coding_style:
  php: false

tools:
# Wait for code coverage to be pushed from travis-ci
  external_code_coverage:
    timeout: 600    # Timeout in seconds.
