language: php

php:
    - 7.1
    - 7.2
    - 7.3

install:
    - composer install --no-interaction --prefer-dist

script:
    - vendor/bin/phpunit --coverage-clover build/coverage/clover.xml
    - ./autofix.sh

#after_script:
#    - vendor/bin/coveralls -v
