language: php

matrix:
  include:
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4
      env: ANALYSIS='true'

install:
  - composer install --no-interaction --prefer-dist

script:
# All PHP versions: run unit tests (functionality)
  - if [[ "$ANALYSIS" != 'true' ]]; then vendor/bin/phpunit ; fi
# Only one PHP version: style/quality checks (code coverage, static analysis)
  - if [[ "$ANALYSIS" == 'true' ]]; then vendor/bin/phpunit --coverage-clover build/coverage/clover.xml ; fi
  - if [[ "$ANALYSIS" == 'true' ]]; then ./run_ci.sh TRAVIS ; fi
  - if [[ "$ANALYSIS" == 'true' ]]; then vendor/bin/phpstan analyse --level 1 src tests ; fi

after_success:
# only upload coverage if coverage was actually generated
  - if [[ "$ANALYSIS" == "true" ]]; then vendor/bin/php-coveralls -v ; fi
