language: php

php:
    - 7.1
    - 7.2
    - 7.3

install:
    - composer install --no-interaction --prefer-dist

script:
    - vendor/bin/phpunit --coverage-clover build/coverage/clover.xml
    - ./autofix.sh CI

after_script:
    - vendor/bin/php-coveralls -v
